### ISSUE TITLE
Mobs are spawned stacked when they shouldn't

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#489]
### Minecraft's Version

1.17.1 pufferfish 

### Plugin's Version

wildstacker b-300

### Describe the bug

So i'm getting a bug , the bug is not hapenning everydays and seems to come after a certain uptime (on the video the server was up since 5Hours , the issue is simple mobs are spawning a certain number like on the video 28 by 28 instead of spawning 1 by 1 on the one block and 100 by 100 from 100 stacked spawners
I'm not getting this everydays and also tried when i removed all my plugin handling mobs spawn or handle creature spawn event
this issue is hapenning since i switched from version 261 to 300

Here is a quick video to explain the bug 
[https://www.youtube.com/watch?v=JSsQZ4nWNUs](url)

### To Reproduce

install wildstacker and AOneBlock from bentobox and hope for the bug to occur, i'm not able to figure how this happen and there is no errors on my logs

**Comment by OmerBenGera** [comment]
> i didnt got that bug since 2 weeks and today i got it

When it happens, use `/ws inspect` and check out the actual mob's stack size and the mob's spawn cause and share the results with me here

**Comment by amarcais53** [comment]
okay i'll send it when it happen again

**Comment by amarcais53** [comment]
![image](https://user-images.githubusercontent.com/62488520/163429930-47d9009d-ed73-427c-81fe-296608e313d7.png)
this is what i see when the bug is here , they are spawning 45 by 45 for now and its increasing with the time , it was 4 by 4 a few hours ago

**Comment by amarcais53** [comment]
@OmerBenGera

**Comment by amarcais53** [comment]
there is no errors in logs

**Comment by amarcais53** [comment]
even with 6000 spawners they are spawning 45 by 45 
![image](https://user-images.githubusercontent.com/62488520/163434228-34b6a326-4660-4627-9f7f-d0adfa0d2595.png)

**Comment by amarcais53** [comment]
another thing after they spawn 1 time 45 the next spawn from spawner spawn 14k by 14k (there was 6k spawners)

**Comment by amarcais53** [comment]
https://user-images.githubusercontent.com/62488520/163435343-ad7c4f47-ced4-446e-be13-08ff97149c27.mp4

**Comment by OmerBenGera** [comment]
Hows a spawner related to ONeBlock?
It seems like an issue that is not related to the oneblock, am I wrong?

**Comment by amarcais53** [comment]
No it’s not this is why I opened the issue there since when it’s happening on the oneblock it’s also happening on spawners form wildstacker as well and since all mobs on my server are handled by wildstacker there is not natural spawn , you renamed the issue to a bug on Aoneblock but it’s not , I have this issue since I updated wildstacker from an old build to latest

**Comment by amarcais53** [comment]
should i send you my config ?

**Comment by OmerBenGera** [comment]
> should i send you my config ?

Sure, may help :)

**Comment by amarcais53** [comment]
i could send you my whole wilstacker file
[WildStacker.zip](https://github.com/BG-Software-LLC/WildStacker/files/8499909/WildStacker.zip)
i can also add you as subuser to my test server that i host on my dédicated like that you can do your test when it happen

**Comment by amarcais53** [comment]
i have more info i dont know if that can help but i have a very large player base so the DB is also big and today the bug came and before the restart there was almost 8.000.000 rabbit stacked and after the restart there was only 1.000.000 remaning , could it be a database issue ? 
![image](https://user-images.githubusercontent.com/62488520/163689136-f1ca61b5-8ccc-442f-9e45-3f7fa1b31d58.png)

**Comment by OmerBenGera** [comment]
> i have more info i dont know if that can help but i have a very large player base so the DB is also big and today the bug came and before the restart there was almost 8.000.000 rabbit stacked and after the restart there was only 1.000.000 remaning , could it be a database issue ? ![image](https://user-images.githubusercontent.com/62488520/163689136-f1ca61b5-8ccc-442f-9e45-3f7fa1b31d58.png)
> 
> ws stats [21:39:45 INFO]: WildStacker Stats:
> 
> * Stacked Entities: (Loaded: 440, Unloaded: 0)
> * Stacked Items: (Loaded: 237, Unloaded: 0)
> * Stacked Spawners: (Loaded: 698, Unloaded: 5374)
> * Stacked Barrels: (Loaded: 0, Unloaded: 0)

Entities data is not saved to database

**Comment by amarcais53** [comment]
after now 2 weeks im not able to manage to get the bug on a exact copy of the server so i guess its hapenning with a lot of players, is seems to always happen at player peak or after player peak so around 8p and 0am im gonna check the logs lines by lines later to see if its not caused by a player doing a weird command or something like that

**Comment by amarcais53** [comment]
i still have no clue how to reproduce it but this bug is really annoying , restarting the server every 6 hours is my only way to fix it and i dont want to do that , so i rollbacked to an old build until its fixed

**Comment by amarcais53** [comment]
build 261 doesnt have the issue btw

**Comment by amarcais53** [comment]
@OmerBenGera would it be possible to get the build 261 <with the coreportect patch only like that my issue will be fixed

**Comment by amarcais53** [comment]
> @OmerBenGera would it be possible to get the build 261 <with the coreportect patch only like that my issue will be fixed

i really need this since 1 month with this old build and i didnt got the issue lmy only issue is that i cant see who break spawners with coreprotect

**Comment by amarcais53** [comment]
@OmerBenGera please.

**Comment by OmerBenGera** [comment]
> @OmerBenGera please.

I am not making custom builds.
The plugin is open source and you can do that if you wish yourself.
Unless you give me more information about the issue it wont be fixed, as it doesnt happen for me and I cant replicate it.

**Comment by amarcais53** [comment]
how i am supposed to remove all the thing you did after build 261

**Comment by amarcais53** [comment]
also i gave all information i had now you just have do check what you edited on the code to see what could break

**Comment by amarcais53** [comment]
you know what
I'm gonna update version by version until the bug come
when i find it i'll tell you

**Comment by amarcais53** [comment]
I'm currently at build 267 with no issue i'll continue updating slowly

**Comment by amarcais53** [comment]
@OmerBenGera we finally found what build was causing issue it seems to be build 268 since i updated on it the issue is back i hope u will find something

**Comment by amarcais53** [comment]
here is the link https://hub.bg-software.com/job/WildStacker/268/

**Comment by OmerBenGera** [comment]
> @OmerBenGera we finally found what build was causing issue it seems to be build 268 since i updated on it the issue is back i hope u will find something

How do I trigger the issue again?

**Comment by amarcais53** [comment]
I have no idea I’m just running the server with +100 players for the whole day and then the issue occur I could probably give you access to my ptero app like that you should be able to do testing when it happen

**Comment by amarcais53** [comment]
as i can see you did some changes related to future entity tracker could it be that ? https://github.com/BG-Software-LLC/WildStacker/commit/1c7d2a96b0c23cb21665385d4ca63974f78360a1
it looks like everytime the bug start my mobs are spawning 3 by 3 , and slimes are usually splited on 3 when dead i have no idea if this can be related im so bad

**Comment by OmerBenGera** [comment]
I found an issue similar to the one you noticed above.
The slime tracker makes sure to only set sizes to slimes, however the mushroom cows tracker did not. Not only that, it did not reset the data correctly, which caused other mobs to also have their stack sizes set (I noticed skeletons and other mobs while checking it out). I fixed it in latest dev build, hopefully this eliminates the issue you have.

Let me know if it still happens :)

**Comment by amarcais53** [comment]
Oh good I’m happy that I readed the code about the slime part haha I’ll let you know later if it’s fixed it can take some days to be sure

**Comment by amarcais53** [comment]
hey @OmerBenGera its been 7 days since i updated and still not the bug , otherwise im getting 2 other bugs that i didnt had before should i report them here or make a new issue for each, there is no stack trace

**Comment by OmerBenGera** [comment]
> hey @OmerBenGera its been 7 days since i updated and still not the bug , otherwise im getting 2 other bugs that i didnt had before should i report them here or make a new issue for each, there is no stack trace

open new issues regarding them
I am closing this for now :)
