### ISSUE TITLE
Froglight not obtainable with wildstacker installed

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildStacker#563]
### Minecraft's Version

1.19 and 1.19.1

### Plugin's Version

dev b323

### Describe the bug

When a small magma cube is killed by a frog it should drop frog light, this does not occur due to wildstacker being installed.

### To Reproduce

Take a magma cube
Grab a frog
Have the frog kill the magma cube
No frog light drops

### Additional Information

Tested with just wildstacker installed and also on 1.19 and 1.19.1.

**Comment by OmerBenGera** [comment]
Thanks for reporting, it is fixed in latest dev build.
However, because the fix requires changing the loot table, it will not automatically be applied to your loot table file - you can manually edit it to be the following (no update is required for this to get fixed):
```json
{
  "pairs": [
    {
      "chance": 100,
      "items": [
        {
          "type": "MAGMA_CREAM",
          "chance": 25,
          "min": 1,
          "max": 1,
          "looting": true
        }
      ]
    },
    {
      "killer": [
        "WITHER"
      ],
      "chance": 100,
      "items": [
        {
          "type": "WITHER_ROSE",
          "chance": 100
        }
      ]
    },
    {
      "killer": [
        "FROG"
      ],
      "chance": 100,
      "items": [
        {
          "type": "OCHRE_FROGLIGHT",
          "chance": 100
        }
      ]
    }
  ]
}
```

**Comment by Skizzles** [comment]
> ```json
>   "pairs": [
>     {
>       "chance": 100,
>       "items": [
>         {
>           "type": "MAGMA_CREAM",
>           "chance": 25,
>           "min": 1,
>           "max": 1,
>           "looting": true
>         }
>       ]
>     },
>     {
>       "killer": [
>         "WITHER"
>       ],
>       "chance": 100,
>       "items": [
>         {
>           "type": "WITHER_ROSE",
>           "chance": 100
>         }
>       ]
>     },
>     {
>       "killer": [
>         "FROG"
>       ],
>       "chance": 100,
>       "items": [
>         {
>           "type": "OCHRE_FROGLIGHT",
>           "chance": 100
>         }
>       ]
>     }
>   ]
> }
> ```

Will this account for mojangs different frog types?
![image](https://user-images.githubusercontent.com/30563757/182800276-319944e5-c4eb-4d1b-9bfe-bcb7fc98bcba.png)

**Comment by OmerBenGera** [comment]
> > ```json
> >   "pairs": [
> >     {
> >       "chance": 100,
> >       "items": [
> >         {
> >           "type": "MAGMA_CREAM",
> >           "chance": 25,
> >           "min": 1,
> >           "max": 1,
> >           "looting": true
> >         }
> >       ]
> >     },
> >     {
> >       "killer": [
> >         "WITHER"
> >       ],
> >       "chance": 100,
> >       "items": [
> >         {
> >           "type": "WITHER_ROSE",
> >           "chance": 100
> >         }
> >       ]
> >     },
> >     {
> >       "killer": [
> >         "FROG"
> >       ],
> >       "chance": 100,
> >       "items": [
> >         {
> >           "type": "OCHRE_FROGLIGHT",
> >           "chance": 100
> >         }
> >       ]
> >     }
> >   ]
> > }
> > ```
> 
> Will this account for mojangs different frog types? ![image](https://user-images.githubusercontent.com/30563757/182800276-319944e5-c4eb-4d1b-9bfe-bcb7fc98bcba.png)

I don't think so, no.

**Comment by OmerBenGera** [comment]
I fixed it in latest dev build by adding a much more advanced filtering system to loot tables.
The new loot table requires latest dev build and should be like this:
```json
{
  "pairs": [
    {
      "chance": 100,
      "items": [
        {
          "type": "MAGMA_CREAM",
          "chance": 25,
          "min": 1,
          "max": 1,
          "looting": true
        }
      ]
    },
    {
      "killer": [
        "WITHER"
      ],
      "chance": 100,
      "items": [
        {
          "type": "WITHER_ROSE",
          "chance": 100
        }
      ]
    },
    {
      "killer": [
        "FROG"
      ],
      "chance": 100,
      "items": [
        {
          "killer": [
            {
              "type": "FROG",
              "variant": "minecraft:warm"
            }
          ],
          "type": "PEARLESCENT_FROGLIGHT",
          "chance": 100
        },
        {
          "killer": [
            {
              "type": "FROG",
              "variant": "minecraft:cold"
            }
          ],
          "type": "VERDANT_FROGLIGHT",
          "chance": 100
        },
        {
          "killer": [
            {
              "type": "FROG",
              "variant": "minecraft:temperate"
            }
          ],
          "type": "OCHRE_FROGLIGHT",
          "chance": 100
        }
      ]
    }
  ]
}
```

**Comment by Skizzles** [comment]
> I fixed it in latest dev build by adding a much more advanced filtering system to loot tables. The new loot table requires latest dev build and should be like this:
> 
> ```json
> {
>   "pairs": [
>     {
>       "chance": 100,
>       "items": [
>         {
>           "type": "MAGMA_CREAM",
>           "chance": 25,
>           "min": 1,
>           "max": 1,
>           "looting": true
>         }
>       ]
>     },
>     {
>       "killer": [
>         "WITHER"
>       ],
>       "chance": 100,
>       "items": [
>         {
>           "type": "WITHER_ROSE",
>           "chance": 100
>         }
>       ]
>     },
>     {
>       "killer": [
>         "FROG"
>       ],
>       "chance": 100,
>       "items": [
>         {
>           "killer": [
>             {
>               "type": "FROG",
>               "variant": "minecraft:warm"
>             }
>           ],
>           "type": "PEARLESCENT_FROGLIGHT",
>           "chance": 100
>         },
>         {
>           "killer": [
>             {
>               "type": "FROG",
>               "variant": "minecraft:cold"
>             }
>           ],
>           "type": "VERDANT_FROGLIGHT",
>           "chance": 100
>         },
>         {
>           "killer": [
>             {
>               "type": "FROG",
>               "variant": "minecraft:temperate"
>             }
>           ],
>           "type": "OCHRE_FROGLIGHT",
>           "chance": 100
>         }
>       ]
>     }
>   ]
> }
> ```

Tried this with different biomes and am only getting the ocre variant

**Comment by OmerBenGera** [comment]
> > I fixed it in latest dev build by adding a much more advanced filtering system to loot tables. The new loot table requires latest dev build and should be like this:
> > ```json
> > {
> >   "pairs": [
> >     {
> >       "chance": 100,
> >       "items": [
> >         {
> >           "type": "MAGMA_CREAM",
> >           "chance": 25,
> >           "min": 1,
> >           "max": 1,
> >           "looting": true
> >         }
> >       ]
> >     },
> >     {
> >       "killer": [
> >         "WITHER"
> >       ],
> >       "chance": 100,
> >       "items": [
> >         {
> >           "type": "WITHER_ROSE",
> >           "chance": 100
> >         }
> >       ]
> >     },
> >     {
> >       "killer": [
> >         "FROG"
> >       ],
> >       "chance": 100,
> >       "items": [
> >         {
> >           "killer": [
> >             {
> >               "type": "FROG",
> >               "variant": "minecraft:warm"
> >             }
> >           ],
> >           "type": "PEARLESCENT_FROGLIGHT",
> >           "chance": 100
> >         },
> >         {
> >           "killer": [
> >             {
> >               "type": "FROG",
> >               "variant": "minecraft:cold"
> >             }
> >           ],
> >           "type": "VERDANT_FROGLIGHT",
> >           "chance": 100
> >         },
> >         {
> >           "killer": [
> >             {
> >               "type": "FROG",
> >               "variant": "minecraft:temperate"
> >             }
> >           ],
> >           "type": "OCHRE_FROGLIGHT",
> >           "chance": 100
> >         }
> >       ]
> >     }
> >   ]
> > }
> > ```
> 
> Tried this with different biomes and am only getting the ocre variant

Make sure you use b328 and the exact loot table above. Make sure the loot table is saved and that you restarted the server
I tested it multiple times and it worked fantastically fine for me.

**Comment by Skizzles** [comment]
@OmerBenGera 
https://screenshots.skizzles.me/wAnA3/duPUGeFi29.mp4

Still occurring, I tested this without any plugins installed previously. Just used plugman and this existing environment. Might be due to using Purpur-1.19.2-1762? (Used purpur previously as well).

**Comment by OmerBenGera** [comment]
> @OmerBenGera https://screenshots.skizzles.me/wAnA3/duPUGeFi29.mp4
> 
> Still occurring, I tested this without any plugins installed previously. Just used plugman and this existing environment. Might be due to using Purpur-1.19.2-1762? (Used purpur previously as well).

As I wrote above, use latest dev build and make sure yoy use the loot table from above. If it still doesnt work, try it on a server with only WildStacker installed.

**Comment by Skizzles** [comment]
![image](https://user-images.githubusercontent.com/30563757/187149105-003777cc-9566-4eda-b332-167c81d40f14.png)

https://screenshots.skizzles.me/wAnA3/KaNAMIdA93.mp4

**Comment by OmerBenGera** [comment]
I checked it again and it works flawlessly fine.
Send me your magma_cube.json file as well as your session logs.

**Comment by Skizzles** [comment]
Fixed, I accidently put the magma cube data into the frog file.
